import Foundation

extension AppLanguage {
    static let cloudSyncTranslations: [AppLanguage: [String: String]] = [
        .french: [
            "Choose Note Storage": "Choisir le stockage des notes",
            "Choose where your notes live": "Choisissez où vivent vos notes",
            "You can change this later in Settings.": "Vous pourrez modifier ce choix plus tard dans Réglages.",
            "Local only": "Uniquement en local",
            "Sync with iCloud": "Synchroniser avec iCloud",
            "Notes and images stay on this Mac. Nothing is uploaded to iCloud.": "Les notes et images restent sur ce Mac. Rien n’est envoyé vers iCloud.",
            "Keep notes and images available on your Apple devices using the same Apple Account.": "Gardez vos notes et images disponibles sur vos appareils Apple utilisant le même compte Apple.",
            "Recommended for privacy": "Recommandé pour la confidentialité",
            "Your notes always remain available offline on this Mac.": "Vos notes restent toujours disponibles hors ligne sur ce Mac.",
            "Continue": "Continuer",
            "Storage & Sync": "Stockage et synchronisation",
            "Stored only on this Mac": "Stocké uniquement sur ce Mac",
            "Checking iCloud account...": "Vérification du compte iCloud…",
            "Syncing...": "Synchronisation…",
            "Up to date": "À jour",
            "Offline. Changes will sync when the connection returns.": "Hors ligne. Les modifications seront synchronisées au retour de la connexion.",
            "Sign in to iCloud in System Settings to sync.": "Connectez-vous à iCloud dans Réglages Système pour synchroniser.",
            "iCloud sync is unavailable in this build.": "La synchronisation iCloud n’est pas disponible dans cette version.",
            "Sync couldn't finish: %@": "La synchronisation n’a pas pu se terminer : %@",
            "Sync Now": "Synchroniser maintenant",
            "Pinaday always saves a local offline copy first.": "Pinaday enregistre toujours d’abord une copie locale hors ligne.",
            "Choose Local only to keep everything on this Mac, or Sync with iCloud to use the same notes on your Apple devices.": "Choisissez Uniquement en local pour tout garder sur ce Mac, ou Synchroniser avec iCloud pour retrouver les mêmes notes sur vos appareils Apple."
        ],
        .spanish: [
            "Choose Note Storage": "Elegir almacenamiento de notas",
            "Choose where your notes live": "Elige dónde guardar tus notas",
            "You can change this later in Settings.": "Puedes cambiarlo más tarde en Ajustes.",
            "Local only": "Solo local",
            "Sync with iCloud": "Sincronizar con iCloud",
            "Notes and images stay on this Mac. Nothing is uploaded to iCloud.": "Las notas e imágenes permanecen en este Mac. No se sube nada a iCloud.",
            "Keep notes and images available on your Apple devices using the same Apple Account.": "Mantén las notas e imágenes disponibles en tus dispositivos Apple con la misma cuenta de Apple.",
            "Recommended for privacy": "Recomendado para privacidad",
            "Your notes always remain available offline on this Mac.": "Tus notas siempre están disponibles sin conexión en este Mac.",
            "Continue": "Continuar",
            "Storage & Sync": "Almacenamiento y sincronización",
            "Stored only on this Mac": "Guardado solo en este Mac",
            "Checking iCloud account...": "Comprobando la cuenta de iCloud…",
            "Syncing...": "Sincronizando…",
            "Up to date": "Actualizado",
            "Offline. Changes will sync when the connection returns.": "Sin conexión. Los cambios se sincronizarán cuando vuelva la conexión.",
            "Sign in to iCloud in System Settings to sync.": "Inicia sesión en iCloud desde Ajustes del Sistema para sincronizar.",
            "iCloud sync is unavailable in this build.": "La sincronización con iCloud no está disponible en esta versión.",
            "Sync couldn't finish: %@": "No se pudo completar la sincronización: %@",
            "Sync Now": "Sincronizar ahora",
            "Pinaday always saves a local offline copy first.": "Pinaday siempre guarda primero una copia local sin conexión.",
            "Choose Local only to keep everything on this Mac, or Sync with iCloud to use the same notes on your Apple devices.": "Elige Solo local para guardarlo todo en este Mac, o Sincronizar con iCloud para usar las mismas notas en tus dispositivos Apple."
        ],
        .simplifiedChinese: [
            "Choose Note Storage": "选择笔记存储方式",
            "Choose where your notes live": "选择笔记的存储位置",
            "You can change this later in Settings.": "之后可随时在设置中更改。",
            "Local only": "仅本地存储",
            "Sync with iCloud": "使用 iCloud 同步",
            "Notes and images stay on this Mac. Nothing is uploaded to iCloud.": "笔记和图片仅保存在这台 Mac，不会上传到 iCloud。",
            "Keep notes and images available on your Apple devices using the same Apple Account.": "在使用同一 Apple 账户的 Apple 设备间同步笔记和图片。",
            "Recommended for privacy": "隐私优先推荐",
            "Your notes always remain available offline on this Mac.": "笔记始终可在这台 Mac 上离线使用。",
            "Continue": "继续",
            "Storage & Sync": "存储与同步",
            "Stored only on this Mac": "仅存储在这台 Mac",
            "Checking iCloud account...": "正在检查 iCloud 账户…",
            "Syncing...": "正在同步…",
            "Up to date": "已是最新",
            "Offline. Changes will sync when the connection returns.": "当前离线，恢复连接后将自动同步更改。",
            "Sign in to iCloud in System Settings to sync.": "请在系统设置中登录 iCloud 以进行同步。",
            "iCloud sync is unavailable in this build.": "此版本无法使用 iCloud 同步。",
            "Sync couldn't finish: %@": "同步未完成：%@",
            "Sync Now": "立即同步",
            "Pinaday always saves a local offline copy first.": "Pinaday 始终会先保存一份本地离线副本。",
            "Choose Local only to keep everything on this Mac, or Sync with iCloud to use the same notes on your Apple devices.": "选择“仅本地存储”可将所有内容保留在这台 Mac；选择“使用 iCloud 同步”可在 Apple 设备上使用相同的笔记。"
        ],
        .japanese: [
            "Choose Note Storage": "ノートの保存先を選択",
            "Choose where your notes live": "ノートの保存先を選んでください",
            "You can change this later in Settings.": "この設定は後で変更できます。",
            "Local only": "このMacのみ",
            "Sync with iCloud": "iCloudで同期",
            "Notes and images stay on this Mac. Nothing is uploaded to iCloud.": "ノートと画像はこのMacだけに保存され、iCloudにはアップロードされません。",
            "Keep notes and images available on your Apple devices using the same Apple Account.": "同じApple Accountを使うAppleデバイスでノートと画像を利用できます。",
            "Recommended for privacy": "プライバシー重視におすすめ",
            "Your notes always remain available offline on this Mac.": "ノートはこのMacで常にオフライン利用できます。",
            "Continue": "続ける",
            "Storage & Sync": "保存と同期",
            "Stored only on this Mac": "このMacだけに保存",
            "Checking iCloud account...": "iCloudアカウントを確認中…",
            "Syncing...": "同期中…",
            "Up to date": "最新",
            "Offline. Changes will sync when the connection returns.": "オフラインです。接続が戻ると変更が同期されます。",
            "Sign in to iCloud in System Settings to sync.": "同期するにはシステム設定でiCloudにサインインしてください。",
            "iCloud sync is unavailable in this build.": "このビルドではiCloud同期を利用できません。",
            "Sync couldn't finish: %@": "同期を完了できませんでした：%@",
            "Sync Now": "今すぐ同期",
            "Pinaday always saves a local offline copy first.": "Pinadayは常に最初にローカルのオフラインコピーを保存します。",
            "Choose Local only to keep everything on this Mac, or Sync with iCloud to use the same notes on your Apple devices.": "「このMacのみ」ならすべてをこのMacに保存し、「iCloudで同期」ならAppleデバイスで同じノートを利用できます。"
        ],
        .korean: [
            "Choose Note Storage": "노트 저장 위치 선택",
            "Choose where your notes live": "노트를 저장할 위치를 선택하세요",
            "You can change this later in Settings.": "나중에 설정에서 변경할 수 있습니다.",
            "Local only": "이 Mac에만 저장",
            "Sync with iCloud": "iCloud로 동기화",
            "Notes and images stay on this Mac. Nothing is uploaded to iCloud.": "노트와 이미지는 이 Mac에만 남으며 iCloud에 업로드되지 않습니다.",
            "Keep notes and images available on your Apple devices using the same Apple Account.": "같은 Apple Account를 사용하는 Apple 기기에서 노트와 이미지를 사용할 수 있습니다.",
            "Recommended for privacy": "개인정보 보호 권장",
            "Your notes always remain available offline on this Mac.": "노트는 이 Mac에서 항상 오프라인으로 사용할 수 있습니다.",
            "Continue": "계속",
            "Storage & Sync": "저장 및 동기화",
            "Stored only on this Mac": "이 Mac에만 저장됨",
            "Checking iCloud account...": "iCloud 계정 확인 중…",
            "Syncing...": "동기화 중…",
            "Up to date": "최신 상태",
            "Offline. Changes will sync when the connection returns.": "오프라인입니다. 연결되면 변경 사항이 동기화됩니다.",
            "Sign in to iCloud in System Settings to sync.": "동기화하려면 시스템 설정에서 iCloud에 로그인하세요.",
            "iCloud sync is unavailable in this build.": "이 빌드에서는 iCloud 동기화를 사용할 수 없습니다.",
            "Sync couldn't finish: %@": "동기화를 완료하지 못했습니다: %@",
            "Sync Now": "지금 동기화",
            "Pinaday always saves a local offline copy first.": "Pinaday는 항상 로컬 오프라인 사본을 먼저 저장합니다.",
            "Choose Local only to keep everything on this Mac, or Sync with iCloud to use the same notes on your Apple devices.": "이 Mac에만 저장을 선택하면 모든 내용을 이 Mac에 보관하고, iCloud로 동기화를 선택하면 Apple 기기에서 같은 노트를 사용할 수 있습니다."
        ],
        .german: [
            "Choose Note Storage": "Notizspeicher wählen",
            "Choose where your notes live": "Wählen Sie den Speicherort Ihrer Notizen",
            "You can change this later in Settings.": "Sie können dies später in den Einstellungen ändern.",
            "Local only": "Nur lokal",
            "Sync with iCloud": "Mit iCloud synchronisieren",
            "Notes and images stay on this Mac. Nothing is uploaded to iCloud.": "Notizen und Bilder bleiben auf diesem Mac. Nichts wird in iCloud hochgeladen.",
            "Keep notes and images available on your Apple devices using the same Apple Account.": "Notizen und Bilder sind auf Ihren Apple-Geräten mit demselben Apple Account verfügbar.",
            "Recommended for privacy": "Für Datenschutz empfohlen",
            "Your notes always remain available offline on this Mac.": "Ihre Notizen bleiben auf diesem Mac immer offline verfügbar.",
            "Continue": "Fortfahren",
            "Storage & Sync": "Speicher & Synchronisierung",
            "Stored only on this Mac": "Nur auf diesem Mac gespeichert",
            "Checking iCloud account...": "iCloud-Account wird geprüft…",
            "Syncing...": "Synchronisieren…",
            "Up to date": "Aktuell",
            "Offline. Changes will sync when the connection returns.": "Offline. Änderungen werden synchronisiert, sobald die Verbindung zurückkehrt.",
            "Sign in to iCloud in System Settings to sync.": "Melden Sie sich in den Systemeinstellungen bei iCloud an.",
            "iCloud sync is unavailable in this build.": "iCloud-Synchronisierung ist in diesem Build nicht verfügbar.",
            "Sync couldn't finish: %@": "Synchronisierung fehlgeschlagen: %@",
            "Sync Now": "Jetzt synchronisieren",
            "Pinaday always saves a local offline copy first.": "Pinaday speichert immer zuerst eine lokale Offline-Kopie.",
            "Choose Local only to keep everything on this Mac, or Sync with iCloud to use the same notes on your Apple devices.": "Wählen Sie Nur lokal, um alles auf diesem Mac zu behalten, oder Mit iCloud synchronisieren, um dieselben Notizen auf Ihren Apple-Geräten zu nutzen."
        ],
        .portugueseBrazil: [
            "Choose Note Storage": "Escolher armazenamento das notas",
            "Choose where your notes live": "Escolha onde suas notas ficam",
            "You can change this later in Settings.": "Você pode mudar isso depois nos Ajustes.",
            "Local only": "Somente local",
            "Sync with iCloud": "Sincronizar com o iCloud",
            "Notes and images stay on this Mac. Nothing is uploaded to iCloud.": "Notas e imagens ficam neste Mac. Nada é enviado ao iCloud.",
            "Keep notes and images available on your Apple devices using the same Apple Account.": "Mantenha notas e imagens disponíveis nos dispositivos Apple com a mesma Conta Apple.",
            "Recommended for privacy": "Recomendado para privacidade",
            "Your notes always remain available offline on this Mac.": "Suas notas permanecem disponíveis offline neste Mac.",
            "Continue": "Continuar",
            "Storage & Sync": "Armazenamento e sincronização",
            "Stored only on this Mac": "Armazenado somente neste Mac",
            "Checking iCloud account...": "Verificando a conta do iCloud…",
            "Syncing...": "Sincronizando…",
            "Up to date": "Atualizado",
            "Offline. Changes will sync when the connection returns.": "Offline. As alterações serão sincronizadas quando a conexão voltar.",
            "Sign in to iCloud in System Settings to sync.": "Inicie sessão no iCloud nos Ajustes do Sistema para sincronizar.",
            "iCloud sync is unavailable in this build.": "A sincronização com o iCloud não está disponível nesta versão.",
            "Sync couldn't finish: %@": "Não foi possível concluir a sincronização: %@",
            "Sync Now": "Sincronizar agora",
            "Pinaday always saves a local offline copy first.": "O Pinaday sempre salva primeiro uma cópia local offline.",
            "Choose Local only to keep everything on this Mac, or Sync with iCloud to use the same notes on your Apple devices.": "Escolha Somente local para manter tudo neste Mac ou Sincronizar com o iCloud para usar as mesmas notas nos seus dispositivos Apple."
        ]
    ]
}
