import Foundation

enum AppLanguage: String, Codable, CaseIterable, Identifiable {
    case english
    case french
    case spanish
    case simplifiedChinese
    case japanese
    case korean
    case german
    case portugueseBrazil

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english: return "English"
        case .french: return "Français"
        case .spanish: return "Español"
        case .simplifiedChinese: return "简体中文"
        case .japanese: return "日本語"
        case .korean: return "한국어"
        case .german: return "Deutsch"
        case .portugueseBrazil: return "Português (Brasil)"
        }
    }

    var locale: Locale {
        Locale(identifier: localeIdentifier)
    }

    var localeIdentifier: String {
        switch self {
        case .english: return "en_US"
        case .french: return "fr_FR"
        case .spanish: return "es_ES"
        case .simplifiedChinese: return "zh_Hans_CN"
        case .japanese: return "ja_JP"
        case .korean: return "ko_KR"
        case .german: return "de_DE"
        case .portugueseBrazil: return "pt_BR"
        }
    }

    func localized(_ key: String) -> String {
        Self.translations[self]?[key]
            ?? Self.cloudSyncTranslations[self]?[key]
            ?? Self.helpTranslations[self]?[key]
            ?? key
    }

    func matchCount(_ count: Int) -> String {
        switch self {
        case .english:
            return count == 1 ? "1 match" : "\(count) matches"
        case .french:
            return count == 1 ? "1 résultat" : "\(count) résultats"
        case .spanish:
            return count == 1 ? "1 coincidencia" : "\(count) coincidencias"
        case .simplifiedChinese:
            return "\(count) 个匹配项"
        case .japanese:
            return "\(count) 件一致"
        case .korean:
            return "\(count)개 일치"
        case .german:
            return count == 1 ? "1 Treffer" : "\(count) Treffer"
        case .portugueseBrazil:
            return count == 1 ? "1 resultado" : "\(count) resultados"
        }
    }

    func returnAccessibilityLabel(date: String) -> String {
        String(format: localized("Return to %@"), locale: locale, date)
    }

    func returnTooltip(date: String) -> String {
        String(format: localized("Return to %@, the day you searched from"), locale: locale, date)
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .french: [
            "About Pinaday": "À propos de Pinaday",
            "File": "Fichier",
            "Close Window": "Fermer la fenêtre",
            "Pinaday Quick Start": "Prise en main de Pinaday",
            "Pinaday Help": "Aide Pinaday",
            "Search Notes": "Rechercher des notes",
            "A daily Markdown sticky note.": "Une note adhésive Markdown quotidienne.",
            "Version": "Version",
            "Feedback": "Commentaires",
            "Found an issue or have an idea? Send a note directly to the developer.": "Vous avez trouvé un problème ou avez une idée ? Écrivez directement au développeur.",
            "Send Feedback": "Envoyer un commentaire",
            "Settings": "Réglages",
            "Language": "Langue",
            "Theme": "Thème",
            "Yellow": "Jaune",
            "Light": "Clair",
            "Dark": "Sombre",
            "Keep sticky note above other windows": "Garder la note au-dessus des autres fenêtres",
            "Open Pinaday at login": "Ouvrir Pinaday à la connexion",
            "Sticky note opacity": "Opacité de la note",
            "Pinaday will open automatically when you sign in.": "Pinaday s’ouvrira automatiquement à la connexion.",
            "Pinaday will stay closed until you open it.": "Pinaday restera fermé jusqu’à ce que vous l’ouvriez.",
            "Approve Pinaday in System Settings > General > Login Items.": "Autorisez Pinaday dans Réglages Système > Général > Ouverture.",
            "Open at login is not available for this build.": "L’ouverture à la connexion n’est pas disponible dans cette version.",
            "Open at login status is unavailable.": "L’état de l’ouverture à la connexion est indisponible.",
            "Previous day": "Jour précédent",
            "Next day": "Jour suivant",
            "Today": "Aujourd’hui",
            "Back to today": "Revenir à aujourd’hui",
            "Search notes": "Rechercher des notes",
            "Pin window": "Épingler la fenêtre",
            "Unpin window": "Désépingler la fenêtre",
            "Return to %@": "Revenir au %@",
            "Return to %@, the day you searched from": "Revenir au %@, le jour depuis lequel vous avez recherché",
            "Clear search": "Effacer la recherche",
            "No matching notes": "Aucune note correspondante",
            "Pinaday basics": "Les bases de Pinaday",
            "A few things to know for a smoother start.": "Quelques points à connaître pour bien commencer.",
            "Got it": "Compris",
            "Move through days": "Parcourir les jours",
            "Use the arrows to move between days. A Today button appears whenever you are viewing another date.": "Utilisez les flèches pour changer de jour. Un bouton Aujourd’hui apparaît lorsque vous consultez une autre date.",
            "Quick select with /": "Sélection rapide avec /",
            "Type / on an empty line to choose a format.": "Tapez / sur une ligne vide pour choisir un format.",
            "Markdown format": "Format Markdown",
            "Use familiar Markdown: bold text, headings, tasks, dividers, tables, and code blocks.": "Utilisez le Markdown habituel : gras, titres, tâches, séparateurs, tableaux et blocs de code.",
            "Don't show again": "Ne plus afficher",
            "Pinaday will not show this guide at launch.": "Pinaday n’affichera plus ce guide au démarrage.",
            "Show this guide again next launch.": "Afficher de nouveau ce guide au prochain démarrage.",
            "Todo list": "Liste de tâches",
            "Heading": "Titre",
            "Heading 1": "Titre 1",
            "Heading 2": "Titre 2",
            "Heading 3": "Titre 3",
            "Heading 4": "Titre 4",
            "Bulleted list": "Liste à puces",
            "Numbered list": "Liste numérotée",
            "Quote": "Citation",
            "Code block": "Bloc de code",
            "Divider": "Séparateur",
            "Bold": "Gras",
            "Todo": "Tâche",
            "Copy Image": "Copier l’image",
            "Show recognized text": "Afficher le texte reconnu",
            "Hide recognized text": "Masquer le texte reconnu"
        ],
        .spanish: [
            "About Pinaday": "Acerca de Pinaday",
            "File": "Archivo",
            "Close Window": "Cerrar ventana",
            "Pinaday Quick Start": "Inicio rápido de Pinaday",
            "Pinaday Help": "Ayuda de Pinaday",
            "Search Notes": "Buscar notas",
            "A daily Markdown sticky note.": "Una nota adhesiva Markdown diaria.",
            "Version": "Versión",
            "Feedback": "Comentarios",
            "Found an issue or have an idea? Send a note directly to the developer.": "¿Encontraste un problema o tienes una idea? Escribe directamente al desarrollador.",
            "Send Feedback": "Enviar comentarios",
            "Settings": "Ajustes",
            "Language": "Idioma",
            "Theme": "Tema",
            "Yellow": "Amarillo",
            "Light": "Claro",
            "Dark": "Oscuro",
            "Keep sticky note above other windows": "Mantener la nota sobre otras ventanas",
            "Open Pinaday at login": "Abrir Pinaday al iniciar sesión",
            "Sticky note opacity": "Opacidad de la nota",
            "Pinaday will open automatically when you sign in.": "Pinaday se abrirá automáticamente al iniciar sesión.",
            "Pinaday will stay closed until you open it.": "Pinaday permanecerá cerrado hasta que lo abras.",
            "Approve Pinaday in System Settings > General > Login Items.": "Autoriza Pinaday en Ajustes del Sistema > General > Ítems de inicio.",
            "Open at login is not available for this build.": "Abrir al iniciar sesión no está disponible en esta versión.",
            "Open at login status is unavailable.": "El estado de apertura al inicio no está disponible.",
            "Previous day": "Día anterior",
            "Next day": "Día siguiente",
            "Today": "Hoy",
            "Back to today": "Volver a hoy",
            "Search notes": "Buscar notas",
            "Pin window": "Fijar ventana",
            "Unpin window": "Desfijar ventana",
            "Return to %@": "Volver al %@",
            "Return to %@, the day you searched from": "Volver al %@, el día desde el que buscaste",
            "Clear search": "Borrar búsqueda",
            "No matching notes": "No hay notas coincidentes",
            "Pinaday basics": "Conceptos básicos de Pinaday",
            "A few things to know for a smoother start.": "Algunas cosas que conviene saber para empezar mejor.",
            "Got it": "Entendido",
            "Move through days": "Moverse entre días",
            "Use the arrows to move between days. A Today button appears whenever you are viewing another date.": "Usa las flechas para cambiar de día. Aparece un botón Hoy cuando estás viendo otra fecha.",
            "Quick select with /": "Selección rápida con /",
            "Type / on an empty line to choose a format.": "Escribe / en una línea vacía para elegir un formato.",
            "Markdown format": "Formato Markdown",
            "Use familiar Markdown: bold text, headings, tasks, dividers, tables, and code blocks.": "Usa Markdown conocido: negrita, títulos, tareas, separadores, tablas y bloques de código.",
            "Don't show again": "No volver a mostrar",
            "Pinaday will not show this guide at launch.": "Pinaday no mostrará esta guía al iniciar.",
            "Show this guide again next launch.": "Mostrar esta guía de nuevo en el próximo inicio.",
            "Todo list": "Lista de tareas",
            "Heading": "Título",
            "Heading 1": "Título 1",
            "Heading 2": "Título 2",
            "Heading 3": "Título 3",
            "Heading 4": "Título 4",
            "Bulleted list": "Lista con viñetas",
            "Numbered list": "Lista numerada",
            "Quote": "Cita",
            "Code block": "Bloque de código",
            "Divider": "Separador",
            "Bold": "Negrita",
            "Todo": "Tarea",
            "Copy Image": "Copiar imagen",
            "Show recognized text": "Mostrar texto reconocido",
            "Hide recognized text": "Ocultar texto reconocido"
        ],
        .simplifiedChinese: [
            "About Pinaday": "关于 Pinaday",
            "File": "文件",
            "Close Window": "关闭窗口",
            "Pinaday Quick Start": "Pinaday 快速入门",
            "Pinaday Help": "Pinaday 帮助",
            "Search Notes": "搜索笔记",
            "A daily Markdown sticky note.": "每天一页的 Markdown 便签。",
            "Version": "版本",
            "Feedback": "反馈",
            "Found an issue or have an idea? Send a note directly to the developer.": "发现问题或有新想法？直接给开发者发送邮件。",
            "Send Feedback": "发送反馈",
            "Settings": "设置",
            "Language": "语言",
            "Theme": "主题",
            "Yellow": "黄色",
            "Light": "浅色",
            "Dark": "深色",
            "Keep sticky note above other windows": "将便签保持在其他窗口上方",
            "Open Pinaday at login": "登录时打开 Pinaday",
            "Sticky note opacity": "便签透明度",
            "Pinaday will open automatically when you sign in.": "Pinaday 会在你登录时自动打开。",
            "Pinaday will stay closed until you open it.": "Pinaday 会保持关闭，直到你手动打开。",
            "Approve Pinaday in System Settings > General > Login Items.": "请在“系统设置 > 通用 > 登录项”中允许 Pinaday。",
            "Open at login is not available for this build.": "此版本无法使用登录时打开功能。",
            "Open at login status is unavailable.": "无法获取登录时打开状态。",
            "Previous day": "前一天",
            "Next day": "后一天",
            "Today": "今天",
            "Back to today": "回到今天",
            "Search notes": "搜索笔记",
            "Pin window": "置顶窗口",
            "Unpin window": "取消置顶",
            "Return to %@": "返回 %@",
            "Return to %@, the day you searched from": "返回 %@，即开始搜索时的日期",
            "Clear search": "清除搜索",
            "No matching notes": "没有匹配的笔记",
            "Pinaday basics": "Pinaday 基础用法",
            "A few things to know for a smoother start.": "了解这些功能，使用会更顺手。",
            "Got it": "知道了",
            "Move through days": "切换日期",
            "Use the arrows to move between days. A Today button appears whenever you are viewing another date.": "使用箭头切换日期。查看其他日期时会显示“今天”按钮。",
            "Quick select with /": "使用 / 快速选择",
            "Type / on an empty line to choose a format.": "在空行输入 /，即可选择格式。",
            "Markdown format": "Markdown 格式",
            "Use familiar Markdown: bold text, headings, tasks, dividers, tables, and code blocks.": "支持常用 Markdown：粗体、标题、任务、分隔线、表格和代码块。",
            "Don't show again": "不再显示",
            "Pinaday will not show this guide at launch.": "Pinaday 启动时将不再显示此指南。",
            "Show this guide again next launch.": "下次启动时再次显示此指南。",
            "Todo list": "待办列表",
            "Heading": "标题",
            "Heading 1": "一级标题",
            "Heading 2": "二级标题",
            "Heading 3": "三级标题",
            "Heading 4": "四级标题",
            "Bulleted list": "项目符号列表",
            "Numbered list": "编号列表",
            "Quote": "引用",
            "Code block": "代码块",
            "Divider": "分隔线",
            "Bold": "粗体",
            "Todo": "待办",
            "Copy Image": "复制图片",
            "Show recognized text": "显示识别文本",
            "Hide recognized text": "隐藏识别文本"
        ],
        .japanese: [
            "About Pinaday": "Pinaday について",
            "File": "ファイル",
            "Close Window": "ウインドウを閉じる",
            "Pinaday Quick Start": "Pinaday クイックスタート",
            "Pinaday Help": "Pinaday ヘルプ",
            "Search Notes": "ノートを検索",
            "A daily Markdown sticky note.": "日付ごとの Markdown 付箋です。",
            "Version": "バージョン",
            "Feedback": "フィードバック",
            "Found an issue or have an idea? Send a note directly to the developer.": "問題やアイデアがあれば、開発者に直接メッセージを送れます。",
            "Send Feedback": "フィードバックを送信",
            "Settings": "設定",
            "Language": "言語",
            "Theme": "テーマ",
            "Yellow": "イエロー",
            "Light": "ライト",
            "Dark": "ダーク",
            "Keep sticky note above other windows": "付箋をほかのウインドウより手前に表示",
            "Open Pinaday at login": "ログイン時に Pinaday を開く",
            "Sticky note opacity": "付箋の不透明度",
            "Pinaday will open automatically when you sign in.": "ログインすると Pinaday が自動的に開きます。",
            "Pinaday will stay closed until you open it.": "手動で開くまで Pinaday は閉じたままです。",
            "Approve Pinaday in System Settings > General > Login Items.": "システム設定 > 一般 > ログイン項目で Pinaday を許可してください。",
            "Open at login is not available for this build.": "このビルドではログイン時に開く機能を利用できません。",
            "Open at login status is unavailable.": "ログイン時に開く状態を取得できません。",
            "Previous day": "前の日",
            "Next day": "次の日",
            "Today": "今日",
            "Back to today": "今日に戻る",
            "Search notes": "ノートを検索",
            "Pin window": "ウインドウを固定",
            "Unpin window": "ウインドウの固定を解除",
            "Return to %@": "%@ に戻る",
            "Return to %@, the day you searched from": "検索を始めた日 %@ に戻る",
            "Clear search": "検索を消去",
            "No matching notes": "一致するノートはありません",
            "Pinaday basics": "Pinaday の基本",
            "A few things to know for a smoother start.": "快適に使い始めるためのポイントです。",
            "Got it": "わかりました",
            "Move through days": "日付を移動",
            "Use the arrows to move between days. A Today button appears whenever you are viewing another date.": "矢印で日付を移動します。別の日を表示すると「今日」ボタンが現れます。",
            "Quick select with /": "/ でクイック選択",
            "Type / on an empty line to choose a format.": "空の行で / を入力して書式を選びます。",
            "Markdown format": "Markdown 書式",
            "Use familiar Markdown: bold text, headings, tasks, dividers, tables, and code blocks.": "太字、見出し、タスク、区切り線、表、コードブロックなどの Markdown を使えます。",
            "Don't show again": "今後表示しない",
            "Pinaday will not show this guide at launch.": "起動時にこのガイドを表示しません。",
            "Show this guide again next launch.": "次回起動時にこのガイドを表示します。",
            "Todo list": "タスクリスト",
            "Heading": "見出し",
            "Heading 1": "見出し 1",
            "Heading 2": "見出し 2",
            "Heading 3": "見出し 3",
            "Heading 4": "見出し 4",
            "Bulleted list": "箇条書きリスト",
            "Numbered list": "番号付きリスト",
            "Quote": "引用",
            "Code block": "コードブロック",
            "Divider": "区切り線",
            "Bold": "太字",
            "Todo": "タスク",
            "Copy Image": "画像をコピー",
            "Show recognized text": "認識したテキストを表示",
            "Hide recognized text": "認識したテキストを非表示"
        ],
        .korean: [
            "About Pinaday": "Pinaday 정보",
            "File": "파일",
            "Close Window": "윈도우 닫기",
            "Pinaday Quick Start": "Pinaday 빠른 시작",
            "Pinaday Help": "Pinaday 도움말",
            "Search Notes": "노트 검색",
            "A daily Markdown sticky note.": "날짜별 Markdown 스티커 메모입니다.",
            "Version": "버전",
            "Feedback": "피드백",
            "Found an issue or have an idea? Send a note directly to the developer.": "문제를 발견했거나 아이디어가 있나요? 개발자에게 직접 메시지를 보내세요.",
            "Send Feedback": "피드백 보내기",
            "Settings": "설정",
            "Language": "언어",
            "Theme": "테마",
            "Yellow": "노란색",
            "Light": "라이트",
            "Dark": "다크",
            "Keep sticky note above other windows": "메모를 다른 윈도우 위에 유지",
            "Open Pinaday at login": "로그인 시 Pinaday 열기",
            "Sticky note opacity": "메모 불투명도",
            "Pinaday will open automatically when you sign in.": "로그인하면 Pinaday가 자동으로 열립니다.",
            "Pinaday will stay closed until you open it.": "직접 열 때까지 Pinaday는 닫힌 상태로 유지됩니다.",
            "Approve Pinaday in System Settings > General > Login Items.": "시스템 설정 > 일반 > 로그인 항목에서 Pinaday를 허용하세요.",
            "Open at login is not available for this build.": "이 빌드에서는 로그인 시 열기를 사용할 수 없습니다.",
            "Open at login status is unavailable.": "로그인 시 열기 상태를 확인할 수 없습니다.",
            "Previous day": "이전 날",
            "Next day": "다음 날",
            "Today": "오늘",
            "Back to today": "오늘로 돌아가기",
            "Search notes": "노트 검색",
            "Pin window": "윈도우 고정",
            "Unpin window": "윈도우 고정 해제",
            "Return to %@": "%@(으)로 돌아가기",
            "Return to %@, the day you searched from": "검색을 시작한 날인 %@(으)로 돌아가기",
            "Clear search": "검색 지우기",
            "No matching notes": "일치하는 노트 없음",
            "Pinaday basics": "Pinaday 기본 사용법",
            "A few things to know for a smoother start.": "더 편하게 시작하기 위해 알아둘 내용입니다.",
            "Got it": "확인",
            "Move through days": "날짜 이동",
            "Use the arrows to move between days. A Today button appears whenever you are viewing another date.": "화살표로 날짜를 이동하세요. 다른 날짜를 보면 오늘 버튼이 나타납니다.",
            "Quick select with /": "/로 빠르게 선택",
            "Type / on an empty line to choose a format.": "빈 줄에서 /를 입력해 형식을 선택하세요.",
            "Markdown format": "Markdown 형식",
            "Use familiar Markdown: bold text, headings, tasks, dividers, tables, and code blocks.": "굵게, 제목, 작업, 구분선, 표, 코드 블록 등 익숙한 Markdown을 사용할 수 있습니다.",
            "Don't show again": "다시 표시하지 않기",
            "Pinaday will not show this guide at launch.": "시작할 때 이 안내를 표시하지 않습니다.",
            "Show this guide again next launch.": "다음 시작 시 이 안내를 다시 표시합니다.",
            "Todo list": "할 일 목록",
            "Heading": "제목",
            "Heading 1": "제목 1",
            "Heading 2": "제목 2",
            "Heading 3": "제목 3",
            "Heading 4": "제목 4",
            "Bulleted list": "글머리 기호 목록",
            "Numbered list": "번호 매기기 목록",
            "Quote": "인용",
            "Code block": "코드 블록",
            "Divider": "구분선",
            "Bold": "굵게",
            "Todo": "할 일",
            "Copy Image": "이미지 복사",
            "Show recognized text": "인식된 텍스트 표시",
            "Hide recognized text": "인식된 텍스트 숨기기"
        ],
        .german: [
            "About Pinaday": "Über Pinaday",
            "File": "Ablage",
            "Close Window": "Fenster schließen",
            "Pinaday Quick Start": "Pinaday Kurzeinführung",
            "Pinaday Help": "Pinaday Hilfe",
            "Search Notes": "Notizen durchsuchen",
            "A daily Markdown sticky note.": "Eine tägliche Markdown-Haftnotiz.",
            "Version": "Version",
            "Feedback": "Feedback",
            "Found an issue or have an idea? Send a note directly to the developer.": "Problem gefunden oder eine Idee? Schreiben Sie direkt an den Entwickler.",
            "Send Feedback": "Feedback senden",
            "Settings": "Einstellungen",
            "Language": "Sprache",
            "Theme": "Erscheinungsbild",
            "Yellow": "Gelb",
            "Light": "Hell",
            "Dark": "Dunkel",
            "Keep sticky note above other windows": "Notiz über anderen Fenstern halten",
            "Open Pinaday at login": "Pinaday bei der Anmeldung öffnen",
            "Sticky note opacity": "Deckkraft der Notiz",
            "Pinaday will open automatically when you sign in.": "Pinaday wird bei der Anmeldung automatisch geöffnet.",
            "Pinaday will stay closed until you open it.": "Pinaday bleibt geschlossen, bis Sie es öffnen.",
            "Approve Pinaday in System Settings > General > Login Items.": "Erlauben Sie Pinaday unter Systemeinstellungen > Allgemein > Anmeldeobjekte.",
            "Open at login is not available for this build.": "Beim Anmelden öffnen ist in diesem Build nicht verfügbar.",
            "Open at login status is unavailable.": "Der Anmeldestatus ist nicht verfügbar.",
            "Previous day": "Vorheriger Tag",
            "Next day": "Nächster Tag",
            "Today": "Heute",
            "Back to today": "Zurück zu heute",
            "Search notes": "Notizen durchsuchen",
            "Pin window": "Fenster anheften",
            "Unpin window": "Fenster lösen",
            "Return to %@": "Zurück zum %@",
            "Return to %@, the day you searched from": "Zurück zum %@, dem Ausgangstag der Suche",
            "Clear search": "Suche löschen",
            "No matching notes": "Keine passenden Notizen",
            "Pinaday basics": "Pinaday Grundlagen",
            "A few things to know for a smoother start.": "Ein paar Hinweise für einen reibungslosen Start.",
            "Got it": "Verstanden",
            "Move through days": "Zwischen Tagen wechseln",
            "Use the arrows to move between days. A Today button appears whenever you are viewing another date.": "Wechseln Sie mit den Pfeilen zwischen Tagen. Bei einem anderen Datum erscheint die Taste Heute.",
            "Quick select with /": "Schnellauswahl mit /",
            "Type / on an empty line to choose a format.": "Geben Sie / in einer leeren Zeile ein, um ein Format zu wählen.",
            "Markdown format": "Markdown-Format",
            "Use familiar Markdown: bold text, headings, tasks, dividers, tables, and code blocks.": "Nutzen Sie vertrautes Markdown: Fett, Überschriften, Aufgaben, Trennlinien, Tabellen und Codeblöcke.",
            "Don't show again": "Nicht wieder anzeigen",
            "Pinaday will not show this guide at launch.": "Pinaday zeigt diese Einführung beim Start nicht mehr.",
            "Show this guide again next launch.": "Diese Einführung beim nächsten Start wieder anzeigen.",
            "Todo list": "Aufgabenliste",
            "Heading": "Überschrift",
            "Heading 1": "Überschrift 1",
            "Heading 2": "Überschrift 2",
            "Heading 3": "Überschrift 3",
            "Heading 4": "Überschrift 4",
            "Bulleted list": "Aufzählung",
            "Numbered list": "Nummerierte Liste",
            "Quote": "Zitat",
            "Code block": "Codeblock",
            "Divider": "Trennlinie",
            "Bold": "Fett",
            "Todo": "Aufgabe",
            "Copy Image": "Bild kopieren",
            "Show recognized text": "Erkannten Text anzeigen",
            "Hide recognized text": "Erkannten Text ausblenden"
        ],
        .portugueseBrazil: [
            "About Pinaday": "Sobre o Pinaday",
            "File": "Arquivo",
            "Close Window": "Fechar janela",
            "Pinaday Quick Start": "Início rápido do Pinaday",
            "Pinaday Help": "Ajuda do Pinaday",
            "Search Notes": "Buscar notas",
            "A daily Markdown sticky note.": "Uma nota adesiva diária em Markdown.",
            "Version": "Versão",
            "Feedback": "Feedback",
            "Found an issue or have an idea? Send a note directly to the developer.": "Encontrou um problema ou teve uma ideia? Escreva diretamente ao desenvolvedor.",
            "Send Feedback": "Enviar feedback",
            "Settings": "Ajustes",
            "Language": "Idioma",
            "Theme": "Tema",
            "Yellow": "Amarelo",
            "Light": "Claro",
            "Dark": "Escuro",
            "Keep sticky note above other windows": "Manter a nota acima das outras janelas",
            "Open Pinaday at login": "Abrir o Pinaday ao iniciar sessão",
            "Sticky note opacity": "Opacidade da nota",
            "Pinaday will open automatically when you sign in.": "O Pinaday abrirá automaticamente ao iniciar sessão.",
            "Pinaday will stay closed until you open it.": "O Pinaday ficará fechado até você abri-lo.",
            "Approve Pinaday in System Settings > General > Login Items.": "Autorize o Pinaday em Ajustes do Sistema > Geral > Itens de Início.",
            "Open at login is not available for this build.": "Abrir ao iniciar sessão não está disponível nesta versão.",
            "Open at login status is unavailable.": "O estado de abertura no início não está disponível.",
            "Previous day": "Dia anterior",
            "Next day": "Próximo dia",
            "Today": "Hoje",
            "Back to today": "Voltar para hoje",
            "Search notes": "Buscar notas",
            "Pin window": "Fixar janela",
            "Unpin window": "Desafixar janela",
            "Return to %@": "Voltar para %@",
            "Return to %@, the day you searched from": "Voltar para %@, o dia em que você iniciou a busca",
            "Clear search": "Limpar busca",
            "No matching notes": "Nenhuma nota correspondente",
            "Pinaday basics": "Noções básicas do Pinaday",
            "A few things to know for a smoother start.": "Algumas coisas para começar com mais facilidade.",
            "Got it": "Entendi",
            "Move through days": "Navegar pelos dias",
            "Use the arrows to move between days. A Today button appears whenever you are viewing another date.": "Use as setas para mudar de dia. Um botão Hoje aparece ao visualizar outra data.",
            "Quick select with /": "Seleção rápida com /",
            "Type / on an empty line to choose a format.": "Digite / em uma linha vazia para escolher um formato.",
            "Markdown format": "Formato Markdown",
            "Use familiar Markdown: bold text, headings, tasks, dividers, tables, and code blocks.": "Use Markdown conhecido: negrito, títulos, tarefas, divisores, tabelas e blocos de código.",
            "Don't show again": "Não mostrar novamente",
            "Pinaday will not show this guide at launch.": "O Pinaday não mostrará este guia ao iniciar.",
            "Show this guide again next launch.": "Mostrar este guia novamente na próxima inicialização.",
            "Todo list": "Lista de tarefas",
            "Heading": "Título",
            "Heading 1": "Título 1",
            "Heading 2": "Título 2",
            "Heading 3": "Título 3",
            "Heading 4": "Título 4",
            "Bulleted list": "Lista com marcadores",
            "Numbered list": "Lista numerada",
            "Quote": "Citação",
            "Code block": "Bloco de código",
            "Divider": "Divisor",
            "Bold": "Negrito",
            "Todo": "Tarefa",
            "Copy Image": "Copiar imagem",
            "Show recognized text": "Mostrar texto reconhecido",
            "Hide recognized text": "Ocultar texto reconhecido"
        ]
    ]
}
