import Foundation

extension AppLanguage {
    static let helpTranslations: [AppLanguage: [String: String]] = [
        .french: [
            "A daily Markdown sticky note with checkable tasks, pasted images, and one note per date.": "Une note adhésive Markdown quotidienne avec des tâches cochables, des images collées et une note par date.",
            "Daily Pages": "Pages quotidiennes",
            "Move between days": "Parcourir les jours",
            "Use the left and right arrow buttons in the header.": "Utilisez les flèches gauche et droite dans l’en-tête.",
            "Back to today": "Revenir à aujourd’hui",
            "A Today button appears only when you are viewing another date.": "Le bouton Aujourd’hui apparaît uniquement lorsque vous consultez une autre date.",
            "Return from search": "Revenir après une recherche",
            "After opening a search result, use the return-date button to go back to the day you searched from.": "Après avoir ouvert un résultat, utilisez le bouton de retour pour revenir au jour depuis lequel vous avez lancé la recherche.",
            "Pinned note": "Note épinglée",
            "Use the pin button to keep the sticky note above other windows.": "Utilisez l’épingle pour garder la note au-dessus des autres fenêtres.",
            "Markdown Basics": "Bases de Markdown",
            "Italic": "Italique",
            "Headings": "Titres",
            "Inline code": "Code en ligne",
            "Strikethrough": "Barré",
            "Lists and Tasks": "Listes et tâches",
            "Click the checkbox to toggle it. The standard unchecked syntax is - [ ].": "Cliquez sur la case pour changer son état. La syntaxe standard non cochée est - [ ].",
            "Completed todo": "Tâche terminée",
            "Completed tasks use x inside the brackets.": "Les tâches terminées utilisent un x entre les crochets.",
            "Nested todos": "Tâches imbriquées",
            "Tab moves a task in one level. Shift-Tab moves it back out.": "Tab décale une tâche d’un niveau. Maj-Tab la ramène au niveau précédent.",
            "Continue a list": "Continuer une liste",
            "Return creates the next todo, bullet, number, quote, or code line.": "Retour crée la tâche, puce, numérotation, citation ou ligne de code suivante.",
            "Soft line": "Retour à la ligne simple",
            "Shift-Return adds a continuation line without creating a new checkbox or marker.": "Maj-Retour ajoute une ligne de continuation sans nouvelle case ni marqueur.",
            "Editing": "Édition",
            "Undo and redo": "Annuler et rétablir",
            "Use Cmd-Z to undo and Shift-Cmd-Z to redo.": "Utilisez Cmd-Z pour annuler et Maj-Cmd-Z pour rétablir.",
            "Cut current line": "Couper la ligne actuelle",
            "If no text is selected, Cmd-X cuts the whole line where the caret is.": "Si aucun texte n’est sélectionné, Cmd-X coupe toute la ligne du curseur.",
            "Copy and paste tasks": "Copier et coller des tâches",
            "Task checkbox Markdown is preserved when copying and pasting between days.": "Le Markdown des cases est conservé lors du copier-coller entre les jours.",
            "Remove an empty task": "Supprimer une tâche vide",
            "Backspace on an empty todo line removes the checkbox marker.": "Retour arrière sur une tâche vide supprime la case.",
            "Slash Menu": "Menu barre oblique",
            "Open the menu": "Ouvrir le menu",
            "Type / on an empty line. Use Up and Down, then Return, or click an item.": "Tapez / sur une ligne vide. Utilisez Haut et Bas puis Retour, ou cliquez sur un élément.",
            "Choose Todo list or type /todo and press Return.": "Choisissez Liste de tâches ou tapez /todo puis Retour.",
            "Choose Heading 1-4 or type /h1, /h2, /h3, or /h4.": "Choisissez Titre 1 à 4 ou tapez /h1, /h2, /h3 ou /h4.",
            "Lists and quote": "Listes et citation",
            "Choose Bulleted list, Numbered list, or Quote.": "Choisissez Liste à puces, Liste numérotée ou Citation.",
            "Code block language": "Langage du bloc de code",
            "Type /code plus a language name, then press Return.": "Tapez /code suivi d’un langage, puis Retour.",
            "Choose Divider or type /--- to insert a horizontal line.": "Choisissez Séparateur ou tapez /--- pour insérer une ligne horizontale.",
            "Images": "Images",
            "Paste an image": "Coller une image",
            "Copy a screenshot or image, then use Cmd-V in the note.": "Copiez une capture ou une image, puis utilisez Cmd-V dans la note.",
            "Move around an image": "Se déplacer autour d’une image",
            "The caret stops before or after the image. One arrow key crosses the image.": "Le curseur s’arrête avant ou après l’image. Une flèche permet de la traverser.",
            "Delete an image": "Supprimer une image",
            "Put the caret beside it and press Delete or Backspace.": "Placez le curseur à côté puis appuyez sur Suppr ou Retour arrière.",
            "Resize an image": "Redimensionner une image",
            "Select the image, then drag the middle-right handle to change width.": "Sélectionnez l’image puis faites glisser la poignée centrale droite pour modifier sa largeur.",
            "Tables and Code": "Tableaux et code",
            "Table": "Tableau",
            "Tables render when the caret is outside them. When the caret is inside, the table stays raw so you can edit rows and columns.": "Les tableaux sont rendus lorsque le curseur est à l’extérieur. À l’intérieur, le Markdown brut reste visible pour modifier lignes et colonnes.",
            "Table separator": "Séparateur de tableau",
            "The second line marks the header separator.": "La deuxième ligne marque la séparation de l’en-tête.",
            "Use fenced Markdown or type /code language. Example: /code swift.": "Utilisez un bloc Markdown délimité ou tapez /code langage. Exemple : /code swift.",
            "Choose Yellow, Light, or Dark in Settings.": "Choisissez Jaune, Clair ou Sombre dans Réglages.",
            "Opacity": "Opacité",
            "Set the sticky note opacity from fully visible to invisible.": "Réglez l’opacité de totalement visible à invisible.",
            "Window behavior": "Comportement de la fenêtre",
            "Pinned state, window size, and position are saved automatically.": "L’épinglage, la taille et la position sont enregistrés automatiquement.",
            "Open at login": "Ouvrir à la connexion",
            "Turn on Open Pinaday at login to start the note automatically when you sign in.": "Activez Ouvrir Pinaday à la connexion pour lancer automatiquement la note lors de votre connexion."
        ],
        .spanish: [
            "A daily Markdown sticky note with checkable tasks, pasted images, and one note per date.": "Una nota adhesiva Markdown diaria con tareas marcables, imágenes pegadas y una nota por fecha.",
            "Daily Pages": "Páginas diarias",
            "Move between days": "Moverse entre días",
            "Use the left and right arrow buttons in the header.": "Usa las flechas izquierda y derecha del encabezado.",
            "Back to today": "Volver a hoy",
            "A Today button appears only when you are viewing another date.": "El botón Hoy solo aparece cuando ves otra fecha.",
            "Return from search": "Volver desde la búsqueda",
            "After opening a search result, use the return-date button to go back to the day you searched from.": "Tras abrir un resultado, usa el botón de retorno para volver al día desde el que buscaste.",
            "Pinned note": "Nota fijada",
            "Use the pin button to keep the sticky note above other windows.": "Usa el botón de fijar para mantener la nota sobre otras ventanas.",
            "Markdown Basics": "Conceptos básicos de Markdown",
            "Italic": "Cursiva",
            "Headings": "Títulos",
            "Inline code": "Código en línea",
            "Strikethrough": "Tachado",
            "Lists and Tasks": "Listas y tareas",
            "Click the checkbox to toggle it. The standard unchecked syntax is - [ ].": "Haz clic en la casilla para cambiar su estado. La sintaxis estándar sin marcar es - [ ].",
            "Completed todo": "Tarea completada",
            "Completed tasks use x inside the brackets.": "Las tareas completadas usan una x dentro de los corchetes.",
            "Nested todos": "Tareas anidadas",
            "Tab moves a task in one level. Shift-Tab moves it back out.": "Tab mueve una tarea un nivel hacia dentro. Mayús-Tab la mueve hacia fuera.",
            "Continue a list": "Continuar una lista",
            "Return creates the next todo, bullet, number, quote, or code line.": "Retorno crea la siguiente tarea, viñeta, número, cita o línea de código.",
            "Soft line": "Línea de continuación",
            "Shift-Return adds a continuation line without creating a new checkbox or marker.": "Mayús-Retorno añade una línea de continuación sin crear otra casilla o marcador.",
            "Editing": "Edición",
            "Undo and redo": "Deshacer y rehacer",
            "Use Cmd-Z to undo and Shift-Cmd-Z to redo.": "Usa Cmd-Z para deshacer y Mayús-Cmd-Z para rehacer.",
            "Cut current line": "Cortar la línea actual",
            "If no text is selected, Cmd-X cuts the whole line where the caret is.": "Si no hay texto seleccionado, Cmd-X corta toda la línea del cursor.",
            "Copy and paste tasks": "Copiar y pegar tareas",
            "Task checkbox Markdown is preserved when copying and pasting between days.": "El Markdown de las casillas se conserva al copiar y pegar entre días.",
            "Remove an empty task": "Eliminar una tarea vacía",
            "Backspace on an empty todo line removes the checkbox marker.": "Retroceso en una tarea vacía elimina la casilla.",
            "Slash Menu": "Menú de barra",
            "Open the menu": "Abrir el menú",
            "Type / on an empty line. Use Up and Down, then Return, or click an item.": "Escribe / en una línea vacía. Usa Arriba y Abajo, luego Retorno, o haz clic en un elemento.",
            "Choose Todo list or type /todo and press Return.": "Elige Lista de tareas o escribe /todo y pulsa Retorno.",
            "Choose Heading 1-4 or type /h1, /h2, /h3, or /h4.": "Elige Título 1-4 o escribe /h1, /h2, /h3 o /h4.",
            "Lists and quote": "Listas y cita",
            "Choose Bulleted list, Numbered list, or Quote.": "Elige Lista con viñetas, Lista numerada o Cita.",
            "Code block language": "Lenguaje del bloque de código",
            "Type /code plus a language name, then press Return.": "Escribe /code y el nombre de un lenguaje, luego Retorno.",
            "Choose Divider or type /--- to insert a horizontal line.": "Elige Separador o escribe /--- para insertar una línea horizontal.",
            "Images": "Imágenes",
            "Paste an image": "Pegar una imagen",
            "Copy a screenshot or image, then use Cmd-V in the note.": "Copia una captura o imagen y usa Cmd-V en la nota.",
            "Move around an image": "Moverse alrededor de una imagen",
            "The caret stops before or after the image. One arrow key crosses the image.": "El cursor se detiene antes o después de la imagen. Una flecha la atraviesa.",
            "Delete an image": "Eliminar una imagen",
            "Put the caret beside it and press Delete or Backspace.": "Coloca el cursor junto a ella y pulsa Suprimir o Retroceso.",
            "Resize an image": "Cambiar el tamaño de una imagen",
            "Select the image, then drag the middle-right handle to change width.": "Selecciona la imagen y arrastra el tirador central derecho para cambiar el ancho.",
            "Tables and Code": "Tablas y código",
            "Table": "Tabla",
            "Tables render when the caret is outside them. When the caret is inside, the table stays raw so you can edit rows and columns.": "Las tablas se renderizan cuando el cursor está fuera. Dentro se mantiene el Markdown sin procesar para editar filas y columnas.",
            "Table separator": "Separador de tabla",
            "The second line marks the header separator.": "La segunda línea marca el separador del encabezado.",
            "Use fenced Markdown or type /code language. Example: /code swift.": "Usa Markdown delimitado o escribe /code lenguaje. Ejemplo: /code swift.",
            "Choose Yellow, Light, or Dark in Settings.": "Elige Amarillo, Claro u Oscuro en Ajustes.",
            "Opacity": "Opacidad",
            "Set the sticky note opacity from fully visible to invisible.": "Ajusta la opacidad desde totalmente visible hasta invisible.",
            "Window behavior": "Comportamiento de la ventana",
            "Pinned state, window size, and position are saved automatically.": "El estado fijado, el tamaño y la posición se guardan automáticamente.",
            "Open at login": "Abrir al iniciar sesión",
            "Turn on Open Pinaday at login to start the note automatically when you sign in.": "Activa Abrir Pinaday al iniciar sesión para abrir la nota automáticamente."
        ],
        .simplifiedChinese: [
            "A daily Markdown sticky note with checkable tasks, pasted images, and one note per date.": "每天一页的 Markdown 便签，支持可勾选任务和粘贴图片。",
            "Daily Pages": "每日页面",
            "Move between days": "切换日期",
            "Use the left and right arrow buttons in the header.": "使用顶部的左右箭头切换日期。",
            "Back to today": "回到今天",
            "A Today button appears only when you are viewing another date.": "查看其他日期时才会显示“今天”按钮。",
            "Return from search": "从搜索结果返回",
            "After opening a search result, use the return-date button to go back to the day you searched from.": "打开搜索结果后，使用返回日期按钮回到开始搜索时的页面。",
            "Pinned note": "置顶便签",
            "Use the pin button to keep the sticky note above other windows.": "使用图钉按钮让便签保持在其他窗口上方。",
            "Markdown Basics": "Markdown 基础",
            "Italic": "斜体",
            "Headings": "标题",
            "Inline code": "行内代码",
            "Strikethrough": "删除线",
            "Lists and Tasks": "列表与任务",
            "Click the checkbox to toggle it. The standard unchecked syntax is - [ ].": "点击复选框切换状态。标准的未完成语法是 - [ ]。",
            "Completed todo": "已完成待办",
            "Completed tasks use x inside the brackets.": "已完成任务在方括号中使用 x。",
            "Nested todos": "嵌套待办",
            "Tab moves a task in one level. Shift-Tab moves it back out.": "Tab 将任务缩进一级，Shift-Tab 将其移出一级。",
            "Continue a list": "继续列表",
            "Return creates the next todo, bullet, number, quote, or code line.": "回车会创建下一个待办、项目符号、编号、引用或代码行。",
            "Soft line": "软换行",
            "Shift-Return adds a continuation line without creating a new checkbox or marker.": "Shift-Return 添加连续行，不创建新的复选框或标记。",
            "Editing": "编辑",
            "Undo and redo": "撤销与重做",
            "Use Cmd-Z to undo and Shift-Cmd-Z to redo.": "使用 Cmd-Z 撤销，Shift-Cmd-Z 重做。",
            "Cut current line": "剪切当前行",
            "If no text is selected, Cmd-X cuts the whole line where the caret is.": "未选择文本时，Cmd-X 会剪切光标所在的整行。",
            "Copy and paste tasks": "复制和粘贴任务",
            "Task checkbox Markdown is preserved when copying and pasting between days.": "在不同日期间复制粘贴时，会保留任务复选框的 Markdown。",
            "Remove an empty task": "删除空任务",
            "Backspace on an empty todo line removes the checkbox marker.": "在空待办行按退格键会移除复选框标记。",
            "Slash Menu": "/ 命令菜单",
            "Open the menu": "打开菜单",
            "Type / on an empty line. Use Up and Down, then Return, or click an item.": "在空行输入 /。使用上下键后按回车，或点击选项。",
            "Choose Todo list or type /todo and press Return.": "选择“待办列表”，或输入 /todo 后按回车。",
            "Choose Heading 1-4 or type /h1, /h2, /h3, or /h4.": "选择一至四级标题，或输入 /h1、/h2、/h3、/h4。",
            "Lists and quote": "列表与引用",
            "Choose Bulleted list, Numbered list, or Quote.": "选择项目符号列表、编号列表或引用。",
            "Code block language": "代码块语言",
            "Type /code plus a language name, then press Return.": "输入 /code 和语言名称，然后按回车。",
            "Choose Divider or type /--- to insert a horizontal line.": "选择分隔线，或输入 /--- 插入水平线。",
            "Images": "图片",
            "Paste an image": "粘贴图片",
            "Copy a screenshot or image, then use Cmd-V in the note.": "复制截图或图片，然后在便签中按 Cmd-V。",
            "Move around an image": "在图片前后移动",
            "The caret stops before or after the image. One arrow key crosses the image.": "光标会停在图片前或后，按一次方向键即可跨过图片。",
            "Delete an image": "删除图片",
            "Put the caret beside it and press Delete or Backspace.": "将光标放在图片旁，然后按 Delete 或退格键。",
            "Resize an image": "调整图片大小",
            "Select the image, then drag the middle-right handle to change width.": "选中图片后，拖动右侧中间的控制柄调整宽度。",
            "Tables and Code": "表格与代码",
            "Table": "表格",
            "Tables render when the caret is outside them. When the caret is inside, the table stays raw so you can edit rows and columns.": "光标在表格外时显示渲染结果；光标进入表格后显示原始 Markdown，便于编辑行和列。",
            "Table separator": "表头分隔行",
            "The second line marks the header separator.": "第二行用于标记表头分隔。",
            "Use fenced Markdown or type /code language. Example: /code swift.": "使用围栏式 Markdown，或输入 /code 语言。例如：/code swift。",
            "Choose Yellow, Light, or Dark in Settings.": "在设置中选择黄色、浅色或深色主题。",
            "Opacity": "透明度",
            "Set the sticky note opacity from fully visible to invisible.": "将便签透明度从完全可见调整到完全透明。",
            "Window behavior": "窗口行为",
            "Pinned state, window size, and position are saved automatically.": "置顶状态、窗口大小和位置会自动保存。",
            "Open at login": "登录时打开",
            "Turn on Open Pinaday at login to start the note automatically when you sign in.": "打开“登录时打开 Pinaday”，登录后便签会自动启动。"
        ],
        .japanese: [
            "A daily Markdown sticky note with checkable tasks, pasted images, and one note per date.": "チェックできるタスクや画像貼り付けに対応した、日付ごとの Markdown 付箋です。",
            "Daily Pages": "日別ページ",
            "Move between days": "日付を移動",
            "Use the left and right arrow buttons in the header.": "ヘッダーの左右の矢印を使います。",
            "Back to today": "今日に戻る",
            "A Today button appears only when you are viewing another date.": "別の日付を表示しているときだけ「今日」ボタンが表示されます。",
            "Return from search": "検索元に戻る",
            "After opening a search result, use the return-date button to go back to the day you searched from.": "検索結果を開いた後、戻る日付ボタンで検索を始めた日に戻れます。",
            "Pinned note": "付箋を固定",
            "Use the pin button to keep the sticky note above other windows.": "ピンボタンで付箋をほかのウインドウより手前に保ちます。",
            "Markdown Basics": "Markdown の基本",
            "Italic": "斜体",
            "Headings": "見出し",
            "Inline code": "インラインコード",
            "Strikethrough": "取り消し線",
            "Lists and Tasks": "リストとタスク",
            "Click the checkbox to toggle it. The standard unchecked syntax is - [ ].": "チェックボックスをクリックして状態を切り替えます。未チェックの標準構文は - [ ] です。",
            "Completed todo": "完了したタスク",
            "Completed tasks use x inside the brackets.": "完了したタスクは角括弧内に x を使います。",
            "Nested todos": "入れ子のタスク",
            "Tab moves a task in one level. Shift-Tab moves it back out.": "Tab で一段深く、Shift-Tab で一段浅くします。",
            "Continue a list": "リストを続ける",
            "Return creates the next todo, bullet, number, quote, or code line.": "Return で次のタスク、箇条書き、番号、引用、コード行を作成します。",
            "Soft line": "継続行",
            "Shift-Return adds a continuation line without creating a new checkbox or marker.": "Shift-Return は新しいチェックボックスや記号なしで継続行を追加します。",
            "Editing": "編集",
            "Undo and redo": "取り消す／やり直す",
            "Use Cmd-Z to undo and Shift-Cmd-Z to redo.": "Cmd-Z で取り消し、Shift-Cmd-Z でやり直します。",
            "Cut current line": "現在の行をカット",
            "If no text is selected, Cmd-X cuts the whole line where the caret is.": "選択がない場合、Cmd-X はカーソルがある行全体をカットします。",
            "Copy and paste tasks": "タスクをコピー＆ペースト",
            "Task checkbox Markdown is preserved when copying and pasting between days.": "日付間でコピー＆ペーストしてもチェックボックスの Markdown は保持されます。",
            "Remove an empty task": "空のタスクを削除",
            "Backspace on an empty todo line removes the checkbox marker.": "空のタスク行で Backspace を押すとチェックボックスが削除されます。",
            "Slash Menu": "スラッシュメニュー",
            "Open the menu": "メニューを開く",
            "Type / on an empty line. Use Up and Down, then Return, or click an item.": "空の行で / を入力します。上下キーと Return、またはクリックで選びます。",
            "Choose Todo list or type /todo and press Return.": "タスクリストを選ぶか、/todo と入力して Return を押します。",
            "Choose Heading 1-4 or type /h1, /h2, /h3, or /h4.": "見出し 1〜4 を選ぶか、/h1、/h2、/h3、/h4 を入力します。",
            "Lists and quote": "リストと引用",
            "Choose Bulleted list, Numbered list, or Quote.": "箇条書き、番号付きリスト、引用から選びます。",
            "Code block language": "コードブロックの言語",
            "Type /code plus a language name, then press Return.": "/code と言語名を入力して Return を押します。",
            "Choose Divider or type /--- to insert a horizontal line.": "区切り線を選ぶか、/--- と入力して水平線を挿入します。",
            "Images": "画像",
            "Paste an image": "画像を貼り付ける",
            "Copy a screenshot or image, then use Cmd-V in the note.": "スクリーンショットや画像をコピーし、ノートで Cmd-V を押します。",
            "Move around an image": "画像の前後を移動",
            "The caret stops before or after the image. One arrow key crosses the image.": "カーソルは画像の前後に止まり、矢印キー一回で画像を越えます。",
            "Delete an image": "画像を削除",
            "Put the caret beside it and press Delete or Backspace.": "画像の横にカーソルを置き、Delete または Backspace を押します。",
            "Resize an image": "画像のサイズを変更",
            "Select the image, then drag the middle-right handle to change width.": "画像を選択し、右中央のハンドルをドラッグして幅を変えます。",
            "Tables and Code": "表とコード",
            "Table": "表",
            "Tables render when the caret is outside them. When the caret is inside, the table stays raw so you can edit rows and columns.": "カーソルが外にあると表を描画し、中にあると行や列を編集できるよう Markdown のまま表示します。",
            "Table separator": "表の区切り",
            "The second line marks the header separator.": "2 行目がヘッダーの区切りです。",
            "Use fenced Markdown or type /code language. Example: /code swift.": "フェンス付き Markdown を使うか、/code 言語と入力します。例：/code swift。",
            "Choose Yellow, Light, or Dark in Settings.": "設定でイエロー、ライト、ダークを選びます。",
            "Opacity": "不透明度",
            "Set the sticky note opacity from fully visible to invisible.": "付箋の不透明度を完全表示から透明まで調整します。",
            "Window behavior": "ウインドウの動作",
            "Pinned state, window size, and position are saved automatically.": "固定状態、ウインドウのサイズと位置は自動保存されます。",
            "Open at login": "ログイン時に開く",
            "Turn on Open Pinaday at login to start the note automatically when you sign in.": "「ログイン時に Pinaday を開く」をオンにすると、ログイン時に自動起動します。"
        ],
        .korean: [
            "A daily Markdown sticky note with checkable tasks, pasted images, and one note per date.": "체크 가능한 작업과 이미지 붙여넣기를 지원하는 날짜별 Markdown 스티커 메모입니다.",
            "Daily Pages": "날짜별 페이지",
            "Move between days": "날짜 이동",
            "Use the left and right arrow buttons in the header.": "상단의 왼쪽 및 오른쪽 화살표를 사용하세요.",
            "Back to today": "오늘로 돌아가기",
            "A Today button appears only when you are viewing another date.": "다른 날짜를 보고 있을 때만 오늘 버튼이 표시됩니다.",
            "Return from search": "검색 전 날짜로 돌아가기",
            "After opening a search result, use the return-date button to go back to the day you searched from.": "검색 결과를 연 뒤 돌아가기 날짜 버튼으로 검색을 시작한 날로 돌아갑니다.",
            "Pinned note": "메모 고정",
            "Use the pin button to keep the sticky note above other windows.": "핀 버튼을 사용해 메모를 다른 윈도우 위에 유지합니다.",
            "Markdown Basics": "Markdown 기본",
            "Italic": "기울임",
            "Headings": "제목",
            "Inline code": "인라인 코드",
            "Strikethrough": "취소선",
            "Lists and Tasks": "목록과 작업",
            "Click the checkbox to toggle it. The standard unchecked syntax is - [ ].": "체크박스를 클릭해 상태를 바꿉니다. 표준 미완료 구문은 - [ ] 입니다.",
            "Completed todo": "완료된 할 일",
            "Completed tasks use x inside the brackets.": "완료된 작업은 대괄호 안에 x를 사용합니다.",
            "Nested todos": "중첩된 할 일",
            "Tab moves a task in one level. Shift-Tab moves it back out.": "Tab은 한 단계 들여쓰고 Shift-Tab은 한 단계 내어씁니다.",
            "Continue a list": "목록 이어쓰기",
            "Return creates the next todo, bullet, number, quote, or code line.": "Return은 다음 할 일, 글머리 기호, 번호, 인용 또는 코드 줄을 만듭니다.",
            "Soft line": "이어지는 줄",
            "Shift-Return adds a continuation line without creating a new checkbox or marker.": "Shift-Return은 새 체크박스나 표식 없이 이어지는 줄을 추가합니다.",
            "Editing": "편집",
            "Undo and redo": "실행 취소 및 다시 실행",
            "Use Cmd-Z to undo and Shift-Cmd-Z to redo.": "Cmd-Z로 실행 취소하고 Shift-Cmd-Z로 다시 실행합니다.",
            "Cut current line": "현재 줄 잘라내기",
            "If no text is selected, Cmd-X cuts the whole line where the caret is.": "선택한 텍스트가 없으면 Cmd-X가 커서가 있는 줄 전체를 잘라냅니다.",
            "Copy and paste tasks": "작업 복사 및 붙여넣기",
            "Task checkbox Markdown is preserved when copying and pasting between days.": "날짜 간 복사 및 붙여넣기 시 체크박스 Markdown이 유지됩니다.",
            "Remove an empty task": "빈 작업 제거",
            "Backspace on an empty todo line removes the checkbox marker.": "빈 할 일 줄에서 Backspace를 누르면 체크박스가 제거됩니다.",
            "Slash Menu": "슬래시 메뉴",
            "Open the menu": "메뉴 열기",
            "Type / on an empty line. Use Up and Down, then Return, or click an item.": "빈 줄에 /를 입력하세요. 위아래 키와 Return을 사용하거나 항목을 클릭합니다.",
            "Choose Todo list or type /todo and press Return.": "할 일 목록을 선택하거나 /todo를 입력하고 Return을 누릅니다.",
            "Choose Heading 1-4 or type /h1, /h2, /h3, or /h4.": "제목 1~4를 선택하거나 /h1, /h2, /h3, /h4를 입력합니다.",
            "Lists and quote": "목록과 인용",
            "Choose Bulleted list, Numbered list, or Quote.": "글머리 기호 목록, 번호 매기기 목록 또는 인용을 선택합니다.",
            "Code block language": "코드 블록 언어",
            "Type /code plus a language name, then press Return.": "/code와 언어 이름을 입력한 뒤 Return을 누릅니다.",
            "Choose Divider or type /--- to insert a horizontal line.": "구분선을 선택하거나 /---를 입력해 가로선을 삽입합니다.",
            "Images": "이미지",
            "Paste an image": "이미지 붙여넣기",
            "Copy a screenshot or image, then use Cmd-V in the note.": "스크린샷이나 이미지를 복사한 뒤 메모에서 Cmd-V를 누릅니다.",
            "Move around an image": "이미지 앞뒤로 이동",
            "The caret stops before or after the image. One arrow key crosses the image.": "커서는 이미지 앞이나 뒤에 멈추며 화살표 키 한 번으로 이미지를 건넙니다.",
            "Delete an image": "이미지 삭제",
            "Put the caret beside it and press Delete or Backspace.": "이미지 옆에 커서를 놓고 Delete 또는 Backspace를 누릅니다.",
            "Resize an image": "이미지 크기 조절",
            "Select the image, then drag the middle-right handle to change width.": "이미지를 선택한 뒤 오른쪽 가운데 핸들을 드래그해 너비를 바꿉니다.",
            "Tables and Code": "표와 코드",
            "Table": "표",
            "Tables render when the caret is outside them. When the caret is inside, the table stays raw so you can edit rows and columns.": "커서가 밖에 있으면 표가 렌더링되고 안에 있으면 행과 열을 편집할 수 있도록 원시 Markdown으로 표시됩니다.",
            "Table separator": "표 구분선",
            "The second line marks the header separator.": "두 번째 줄이 머리글 구분선입니다.",
            "Use fenced Markdown or type /code language. Example: /code swift.": "펜스 Markdown을 사용하거나 /code 언어를 입력하세요. 예: /code swift.",
            "Choose Yellow, Light, or Dark in Settings.": "설정에서 노란색, 라이트 또는 다크를 선택합니다.",
            "Opacity": "불투명도",
            "Set the sticky note opacity from fully visible to invisible.": "메모 불투명도를 완전히 보이는 상태부터 투명까지 조절합니다.",
            "Window behavior": "윈도우 동작",
            "Pinned state, window size, and position are saved automatically.": "고정 상태, 윈도우 크기와 위치가 자동으로 저장됩니다.",
            "Open at login": "로그인 시 열기",
            "Turn on Open Pinaday at login to start the note automatically when you sign in.": "로그인 시 Pinaday 열기를 켜면 로그인할 때 메모가 자동으로 시작됩니다."
        ],
        .german: [
            "A daily Markdown sticky note with checkable tasks, pasted images, and one note per date.": "Eine tägliche Markdown-Haftnotiz mit abhakbaren Aufgaben, eingefügten Bildern und einer Notiz pro Datum.",
            "Daily Pages": "Tagesseiten",
            "Move between days": "Zwischen Tagen wechseln",
            "Use the left and right arrow buttons in the header.": "Verwenden Sie die Pfeile links und rechts in der Kopfzeile.",
            "Back to today": "Zurück zu heute",
            "A Today button appears only when you are viewing another date.": "Die Taste Heute erscheint nur, wenn Sie ein anderes Datum anzeigen.",
            "Return from search": "Von der Suche zurückkehren",
            "After opening a search result, use the return-date button to go back to the day you searched from.": "Nach dem Öffnen eines Suchergebnisses bringt Sie die Rückkehrtaste zum Ausgangstag zurück.",
            "Pinned note": "Angeheftete Notiz",
            "Use the pin button to keep the sticky note above other windows.": "Mit der Pin-Taste bleibt die Notiz über anderen Fenstern.",
            "Markdown Basics": "Markdown-Grundlagen",
            "Italic": "Kursiv",
            "Headings": "Überschriften",
            "Inline code": "Inline-Code",
            "Strikethrough": "Durchgestrichen",
            "Lists and Tasks": "Listen und Aufgaben",
            "Click the checkbox to toggle it. The standard unchecked syntax is - [ ].": "Klicken Sie auf das Kontrollkästchen. Die Standardsyntax für unerledigt ist - [ ].",
            "Completed todo": "Erledigte Aufgabe",
            "Completed tasks use x inside the brackets.": "Erledigte Aufgaben verwenden ein x in den Klammern.",
            "Nested todos": "Verschachtelte Aufgaben",
            "Tab moves a task in one level. Shift-Tab moves it back out.": "Tab rückt eine Aufgabe ein, Umschalt-Tab rückt sie aus.",
            "Continue a list": "Liste fortsetzen",
            "Return creates the next todo, bullet, number, quote, or code line.": "Return erstellt die nächste Aufgabe, Aufzählung, Nummer, das nächste Zitat oder die nächste Codezeile.",
            "Soft line": "Fortsetzungszeile",
            "Shift-Return adds a continuation line without creating a new checkbox or marker.": "Umschalt-Return fügt eine Fortsetzungszeile ohne neues Kontrollkästchen oder Zeichen ein.",
            "Editing": "Bearbeiten",
            "Undo and redo": "Widerrufen und wiederholen",
            "Use Cmd-Z to undo and Shift-Cmd-Z to redo.": "Cmd-Z widerruft, Umschalt-Cmd-Z wiederholt.",
            "Cut current line": "Aktuelle Zeile ausschneiden",
            "If no text is selected, Cmd-X cuts the whole line where the caret is.": "Ohne Auswahl schneidet Cmd-X die gesamte Cursorzeile aus.",
            "Copy and paste tasks": "Aufgaben kopieren und einsetzen",
            "Task checkbox Markdown is preserved when copying and pasting between days.": "Das Markdown der Kontrollkästchen bleibt beim Kopieren zwischen Tagen erhalten.",
            "Remove an empty task": "Leere Aufgabe entfernen",
            "Backspace on an empty todo line removes the checkbox marker.": "Rücktaste in einer leeren Aufgabe entfernt das Kontrollkästchen.",
            "Slash Menu": "Slash-Menü",
            "Open the menu": "Menü öffnen",
            "Type / on an empty line. Use Up and Down, then Return, or click an item.": "Geben Sie / in einer leeren Zeile ein. Wählen Sie mit Auf/Ab und Return oder per Klick.",
            "Choose Todo list or type /todo and press Return.": "Wählen Sie Aufgabenliste oder geben Sie /todo und Return ein.",
            "Choose Heading 1-4 or type /h1, /h2, /h3, or /h4.": "Wählen Sie Überschrift 1–4 oder geben Sie /h1, /h2, /h3 oder /h4 ein.",
            "Lists and quote": "Listen und Zitat",
            "Choose Bulleted list, Numbered list, or Quote.": "Wählen Sie Aufzählung, Nummerierte Liste oder Zitat.",
            "Code block language": "Sprache des Codeblocks",
            "Type /code plus a language name, then press Return.": "Geben Sie /code und einen Sprachnamen ein, dann Return.",
            "Choose Divider or type /--- to insert a horizontal line.": "Wählen Sie Trennlinie oder geben Sie /--- ein.",
            "Images": "Bilder",
            "Paste an image": "Bild einsetzen",
            "Copy a screenshot or image, then use Cmd-V in the note.": "Kopieren Sie einen Screenshot oder ein Bild und drücken Sie Cmd-V.",
            "Move around an image": "Um ein Bild navigieren",
            "The caret stops before or after the image. One arrow key crosses the image.": "Der Cursor stoppt vor oder nach dem Bild. Ein Pfeiltastendruck überquert es.",
            "Delete an image": "Bild löschen",
            "Put the caret beside it and press Delete or Backspace.": "Setzen Sie den Cursor daneben und drücken Sie Entfernen oder Rücktaste.",
            "Resize an image": "Bildgröße ändern",
            "Select the image, then drag the middle-right handle to change width.": "Wählen Sie das Bild und ziehen Sie den rechten mittleren Griff, um die Breite zu ändern.",
            "Tables and Code": "Tabellen und Code",
            "Table": "Tabelle",
            "Tables render when the caret is outside them. When the caret is inside, the table stays raw so you can edit rows and columns.": "Tabellen werden außerhalb des Cursors dargestellt. Innerhalb bleibt Markdown sichtbar, damit Zeilen und Spalten bearbeitet werden können.",
            "Table separator": "Tabellentrenner",
            "The second line marks the header separator.": "Die zweite Zeile markiert den Kopftrenner.",
            "Use fenced Markdown or type /code language. Example: /code swift.": "Verwenden Sie Markdown-Codeblöcke oder /code Sprache. Beispiel: /code swift.",
            "Choose Yellow, Light, or Dark in Settings.": "Wählen Sie Gelb, Hell oder Dunkel in den Einstellungen.",
            "Opacity": "Deckkraft",
            "Set the sticky note opacity from fully visible to invisible.": "Stellen Sie die Deckkraft von vollständig sichtbar bis unsichtbar ein.",
            "Window behavior": "Fensterverhalten",
            "Pinned state, window size, and position are saved automatically.": "Pin-Status, Fenstergröße und Position werden automatisch gespeichert.",
            "Open at login": "Bei Anmeldung öffnen",
            "Turn on Open Pinaday at login to start the note automatically when you sign in.": "Aktivieren Sie Pinaday bei der Anmeldung öffnen, um die Notiz automatisch zu starten."
        ],
        .portugueseBrazil: [
            "A daily Markdown sticky note with checkable tasks, pasted images, and one note per date.": "Uma nota adesiva diária em Markdown com tarefas marcáveis, imagens coladas e uma nota por data.",
            "Daily Pages": "Páginas diárias",
            "Move between days": "Navegar pelos dias",
            "Use the left and right arrow buttons in the header.": "Use as setas esquerda e direita no cabeçalho.",
            "Back to today": "Voltar para hoje",
            "A Today button appears only when you are viewing another date.": "O botão Hoje aparece somente ao visualizar outra data.",
            "Return from search": "Voltar da busca",
            "After opening a search result, use the return-date button to go back to the day you searched from.": "Depois de abrir um resultado, use o botão de retorno para voltar ao dia de origem da busca.",
            "Pinned note": "Nota fixada",
            "Use the pin button to keep the sticky note above other windows.": "Use o botão de fixar para manter a nota acima das outras janelas.",
            "Markdown Basics": "Noções básicas de Markdown",
            "Italic": "Itálico",
            "Headings": "Títulos",
            "Inline code": "Código em linha",
            "Strikethrough": "Tachado",
            "Lists and Tasks": "Listas e tarefas",
            "Click the checkbox to toggle it. The standard unchecked syntax is - [ ].": "Clique na caixa para alternar. A sintaxe padrão desmarcada é - [ ].",
            "Completed todo": "Tarefa concluída",
            "Completed tasks use x inside the brackets.": "Tarefas concluídas usam x dentro dos colchetes.",
            "Nested todos": "Tarefas aninhadas",
            "Tab moves a task in one level. Shift-Tab moves it back out.": "Tab move a tarefa um nível para dentro. Shift-Tab move para fora.",
            "Continue a list": "Continuar uma lista",
            "Return creates the next todo, bullet, number, quote, or code line.": "Return cria a próxima tarefa, marcador, número, citação ou linha de código.",
            "Soft line": "Linha de continuação",
            "Shift-Return adds a continuation line without creating a new checkbox or marker.": "Shift-Return adiciona uma continuação sem nova caixa ou marcador.",
            "Editing": "Edição",
            "Undo and redo": "Desfazer e refazer",
            "Use Cmd-Z to undo and Shift-Cmd-Z to redo.": "Use Cmd-Z para desfazer e Shift-Cmd-Z para refazer.",
            "Cut current line": "Recortar a linha atual",
            "If no text is selected, Cmd-X cuts the whole line where the caret is.": "Sem texto selecionado, Cmd-X recorta toda a linha do cursor.",
            "Copy and paste tasks": "Copiar e colar tarefas",
            "Task checkbox Markdown is preserved when copying and pasting between days.": "O Markdown das caixas é preservado ao copiar e colar entre dias.",
            "Remove an empty task": "Remover tarefa vazia",
            "Backspace on an empty todo line removes the checkbox marker.": "Backspace em uma tarefa vazia remove a caixa.",
            "Slash Menu": "Menu de barra",
            "Open the menu": "Abrir o menu",
            "Type / on an empty line. Use Up and Down, then Return, or click an item.": "Digite / em uma linha vazia. Use Cima e Baixo, depois Return, ou clique em um item.",
            "Choose Todo list or type /todo and press Return.": "Escolha Lista de tarefas ou digite /todo e pressione Return.",
            "Choose Heading 1-4 or type /h1, /h2, /h3, or /h4.": "Escolha Título 1–4 ou digite /h1, /h2, /h3 ou /h4.",
            "Lists and quote": "Listas e citação",
            "Choose Bulleted list, Numbered list, or Quote.": "Escolha Lista com marcadores, Lista numerada ou Citação.",
            "Code block language": "Linguagem do bloco de código",
            "Type /code plus a language name, then press Return.": "Digite /code e o nome da linguagem, depois Return.",
            "Choose Divider or type /--- to insert a horizontal line.": "Escolha Divisor ou digite /--- para inserir uma linha horizontal.",
            "Images": "Imagens",
            "Paste an image": "Colar uma imagem",
            "Copy a screenshot or image, then use Cmd-V in the note.": "Copie uma captura ou imagem e use Cmd-V na nota.",
            "Move around an image": "Mover ao redor de uma imagem",
            "The caret stops before or after the image. One arrow key crosses the image.": "O cursor para antes ou depois da imagem. Uma seta atravessa a imagem.",
            "Delete an image": "Excluir uma imagem",
            "Put the caret beside it and press Delete or Backspace.": "Coloque o cursor ao lado e pressione Delete ou Backspace.",
            "Resize an image": "Redimensionar uma imagem",
            "Select the image, then drag the middle-right handle to change width.": "Selecione a imagem e arraste a alça central direita para alterar a largura.",
            "Tables and Code": "Tabelas e código",
            "Table": "Tabela",
            "Tables render when the caret is outside them. When the caret is inside, the table stays raw so you can edit rows and columns.": "As tabelas são renderizadas quando o cursor está fora. Dentro, o Markdown permanece bruto para editar linhas e colunas.",
            "Table separator": "Separador da tabela",
            "The second line marks the header separator.": "A segunda linha marca o separador do cabeçalho.",
            "Use fenced Markdown or type /code language. Example: /code swift.": "Use Markdown cercado ou digite /code linguagem. Exemplo: /code swift.",
            "Choose Yellow, Light, or Dark in Settings.": "Escolha Amarelo, Claro ou Escuro nos Ajustes.",
            "Opacity": "Opacidade",
            "Set the sticky note opacity from fully visible to invisible.": "Ajuste a opacidade de totalmente visível até invisível.",
            "Window behavior": "Comportamento da janela",
            "Pinned state, window size, and position are saved automatically.": "O estado fixado, o tamanho e a posição são salvos automaticamente.",
            "Open at login": "Abrir ao iniciar sessão",
            "Turn on Open Pinaday at login to start the note automatically when you sign in.": "Ative Abrir o Pinaday ao iniciar sessão para abrir a nota automaticamente."
        ]
    ]
}
